name = "TraitExtraction"
uuid = "38bdcf27-bee4-41ec-96d7-b019897ce2a4"
license = "BSD-2-Clause"
authors = ["Richard Reeve <richard.reeve@glasgow.ac.uk>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
Phylo = "aea672f4-3940-5932-aa44-993d1c3ff149"
PhyloNetworks = "33ad39ac-ed31-50eb-9b15-43d0656eaa72"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
CSV = "0.10"
DataFrames = "1"
Git = "1"
JuliaFormatter = "1"
Logging = "1.6"
Missings = "1"
Phylo = "0.5"
PhyloNetworks = "0.16"
Pkg = "1.6"
ResearchSoftwareMetadata = "0.1.1"
Statistics = "1.6"
Test = "1.6"
Unitful = "1"
XLSX = "0.10"
julia = "1.6.7"

[[author_details]]
name = "Richard Reeve"
orcid = "0000-0003-2589-8091"
email = "richard.reeve@glasgow.ac.uk"

    [[author_details.affiliation]]
    ror = "00vtgdb53"

[extras]
Git = "d7ba0133-e1db-5d97-8f8c-041e4b3a1eb2"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
ResearchSoftwareMetadata = "58378933-4625-47fa-851e-05ee27d397bd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Git", "JuliaFormatter", "Logging", "Pkg", "ResearchSoftwareMetadata", "Test"]
