name = "TraitExtraction"
uuid = "38bdcf27-bee4-41ec-96d7-b019897ce2a4"
authors = ["richardreeve <richard.reeve@glasgow.ac.uk> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
